services:
  - type: web
    name: roshan-portfolio
    env: node
    buildCommand: pnpm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
